/**
 * 
 */
package saveOurPlanet;

import java.util.HashMap;
import java.util.Random;
import java.util.Scanner;

/**
 * 
 */
public class Questions {
	
	public static final String CORRECT_MARK = "U+2705";
	public static final String INCORRECT_MARK = "U+274C";
	
	public HashMap<Integer, String> questionBank;
	public HashMap<Integer, String> answerBank;

	public Questions() {
		questionBank = new HashMap<>();
		answerBank = new HashMap<>();
		loadQuestions();
	}
	
	Scanner scanner = new Scanner(System.in);

	private void loadQuestions() {
		questionBank.put(1, "Question: Which renewable energy source generates the most electricity globally? Please enter a letter.\n"
				+ "A) Wind \n"
				+ "\n"
				+ "B) Hydroelectric \n"
				+ "\n"
				+ "C) Solar \n"
				+ "\n"
				+ "D) Biomass ");
		answerBank.put(1, "B");
		questionBank.put(2, "Question: What is the primary greenhouse gas responsible for global warming? Please enter a letter. \n"
				+ "A) Methane \n"
				+ "\n"
				+ "B) Carbon Dioxide \n"
				+ "\n"
				+ "C) Nitrous Oxide \n"
				+ "\n"
				+ "D) Sulfur Dioxide ");
		answerBank.put(2, "B");
		
		questionBank.put(3, "Question: What percentage of the Earth's water is freshwater? Please enter a letter.\n"
				+ "A) 50% \n"
				+ "\n"
				+ "B) 25% \n"
				+ "\n"
				+ "C) 3% \n"
				+ "\n"
				+ "D) 10% ");
		answerBank.put(3, "C");
		
		questionBank.put(4, "Which greenhouse gas do trees absorb? Please enter a letter.\n"
				+ "A) Methane \n"
				+ "\n"
				+ "B) Carbon Dioxide \n"
				+ "\n"
				+ "C) Nitrous Oxide \n"
				+ "\n"
				+ "D) Sulfur Dioxide ");
		answerBank.put(4, "B");
		
		questionBank.put(5, "What is the most abundant renewable energy source on Earth? Please enter a letter.\n"
				+ "A) Wind Energy\n"
				+ "\n"
				+ "B) Hydropower\n"
				+ "\n"
				+ "C) Solar Energy\n"
				+ "\n"
				+ "D) Geothermal Energy");
		answerBank.put(5, "C");
		
		questionBank.put(6, "Which of the following is NOT a renewable energy source? Please enter a letter.\n"
				+ "A) Wind Power\n"
				+ "\n"
				+ "B) Natural Gas\n"
				+ "\n"
				+ "C) Hydroelectric Power\n"
				+ "\n"
				+ "D) Geothermal Energy");
		answerBank.put(6, "B");
		
		questionBank.put(7, "What percentage of the world's electricity is currently generated by fossil fuels? PLease enter a letter.\n"
				+ "A) 20%\n"
				+ "\n"
				+ "B) 40%\n"
				+ "\n"
				+ "C) 60%\n"
				+ "\n"
				+ "D) 80%"
				+ "\n");
		answerBank.put(7, "C");
		
		questionBank.put(8, "Which country generates the most electricity from wind energy? Please enter a letter.\n"
				+ "A) China\n"
				+ "\n"
				+ "B) Germany\n"
				+ "'n"
				+ "C) USA\n"
				+ "\n"
				+ "D) India");
		answerBank.put(8, "A");
		
		questionBank.put(9, "Which gas is the largest contributor to global warming? Please enter a letter.\n"
		        + "A) Oxygen\n"
		        + "\n"
		        + "B) Carbon Dioxide\n"
		        + "\n"
		        + "C) Nitrogen\n"
		        + "\n"
		        + "D) Methane");
		answerBank.put(9, "B");

		questionBank.put(10, "What is the main cause of ocean acidification? Please enter a letter.\n"
		        + "A) Oil Spills\n"
		        + "\n"
		        + "B) Plastic Pollution\n"
		        + "\n"
		        + "C) Increased CO₂ in the Atmosphere\n"
		        + "\n"
		        + "D) Overfishing");
		answerBank.put(10, "C");

		questionBank.put(11, "Which sector is responsible for the most greenhouse gas emissions? Please enter a letter.\n"
		        + "A) Transportation\n"
		        + "\n"
		        + "B) Agriculture\n"
		        + "\n"
		        + "C) Industry\n"
		        + "\n"
		        + "D) Energy Production");
		answerBank.put(11, "D");

		questionBank.put(12, "Which material takes the longest to decompose? Please enter a letter.\n"
		        + "A) Paper\n"
		        + "\n"
		        + "B) Glass\n"
		        + "\n"
		        + "C) Plastic\n"
		        + "\n"
		        + "D) Aluminum");
		answerBank.put(12, "C");

		questionBank.put(13, "How many plastic bottles are thrown away every minute worldwide? Please enter a letter.\n"
		        + "A) 10,000\n"
		        + "\n"
		        + "B) 50,000\n"
		        + "\n"
		        + "C) 1 Million\n"
		        + "\n"
		        + "D) 5 Million");
		answerBank.put(13, "C");

		questionBank.put(14, "Which of the following is an example of 'reducing' waste? Please enter a letter.\n"
		        + "A) Buying a reusable water bottle instead of plastic ones\n"
		        + "\n"
		        + "B) Throwing away old clothes\n"
		        + "\n"
		        + "C) Using more single-use plastics\n"
		        + "\n"
		        + "D) Burning waste to generate heat");
		answerBank.put(14, "A");

		questionBank.put(15, "Which animal is considered a key indicator of climate change in the Arctic? Please enter a letter.\n"
		        + "A) Penguin\n"
		        + "\n"
		        + "B) Polar Bear\n"
		        + "\n"
		        + "C) Arctic Fox\n"
		        + "\n"
		        + "D) Snow Leopard");
		answerBank.put(15, "B");

		questionBank.put(16, "Deforestation mainly occurs to make space for what? Please enter a letter.\n"
		        + "A) Renewable Energy Projects\n"
		        + "\n"
		        + "B) Urban Expansion\n"
		        + "'n"
		        + "C) Agriculture & Livestock Farming\n"
		        + "\n"
		        + "D) Tourism");
		answerBank.put(16, "C");

		questionBank.put(17, "Which of the following ecosystems stores the most carbon dioxide? Please enter a letter.\n"
		        + "A) Coral Reefs\n"
		        + "\n"
		        + "B) Deserts\n"
		        + "\n"
		        + "C) Tropical Rainforests\n"
		        + "\n"
		        + "D) Grasslands");
		answerBank.put(17, "C");

		questionBank.put(18, "What is the biggest cause of biodiversity loss worldwide? Please enter a letter.\n"
		        + "A) Global Warming\n"
		        + "\n"
		        + "B) Habitat Destruction\n"
		        + "\n"
		        + "C) Overfishing\n"
		        + "\n"
		        + "D) Pollution");
		answerBank.put(18, "B");
		
		questionBank.put(19, "Which of these countries has the highest renewable energy usage?\n"
				+ "A) USA \n"
				+ "\n"
				+ "B) Germany \n"
				+ "\n"
				+ "C) Brazil \n"
				+ "\n"
				+ "D) China");
		answerBank.put(19, "C");
		
		
		
		
	}

	public boolean askQuestion() {
		Random rand = new Random();
		int questionNumber = rand.nextInt(questionBank.size()) + 1;
		String question = questionBank.get(questionNumber);
		String correctAnswer = answerBank.get(questionNumber);

		System.out.println(question);
		System.out.print("Your answer: \n > ");

		String playerAnswer = scanner.nextLine().trim();

		if (playerAnswer.equalsIgnoreCase(correctAnswer.toLowerCase())) {
			System.out.println("Correct! Well Done " + CORRECT_MARK);
			return true;
		} else {
			System.out.println("Sorry, your answer was incorrect " + INCORRECT_MARK);
			return false;
		}
		
	}

}
