/**
 * 
 */
package saveOurPlanet;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

/**
 * 
 */
public class Questions {

	public static final String CORRECT_MARK = "\u2705";
	public static final String INCORRECT_MARK = "\u274C";

	public HashMap<Integer, String> questionBank;
	public HashMap<Integer, String> answerBank;
	public HashMap<Integer, String> ethicsQuestionBank;
	public HashMap<Integer, String> ethicsAnswerBank;

	public Questions() {
		questionBank = new HashMap<>();
		answerBank = new HashMap<>();
		ethicsQuestionBank = new HashMap<>();
		ethicsAnswerBank = new HashMap<>();
		loadQuestions();
		loadEthicsQuestions();
	}

	Scanner scanner = new Scanner(System.in);

	/**
	 * Method to generate a bank of questions, to be called when a player attempts
	 * to purchase or develop a square, or when attempting to reduce the tariff on a
	 * natural disaster square.
	 */
	private void loadQuestions() {
		questionBank.put(1,
				"Question: Which renewable energy source generates the most electricity globally? Please enter a letter.\n"
						+ "A) Wind \n" + "\n" + "B) Hydroelectric \n" + "\n" + "C) Solar \n" + "\n" + "D) Biomass ");
		answerBank.put(1, "B");
		questionBank.put(2,
				"Question: What is the primary greenhouse gas responsible for global warming? Please enter a letter. \n"
						+ "A) Methane \n" + "\n" + "B) Carbon Dioxide \n" + "\n" + "C) Nitrous Oxide \n" + "\n"
						+ "D) Sulfur Dioxide ");
		answerBank.put(2, "B");

		questionBank.put(3, "Question: What percentage of the Earth's water is freshwater? Please enter a letter.\n"
				+ "A) 50% \n" + "\n" + "B) 25% \n" + "\n" + "C) 3% \n" + "\n" + "D) 10% ");
		answerBank.put(3, "C");

		questionBank.put(4, "Which greenhouse gas do trees absorb? Please enter a letter.\n"
				+ "A) Methane \n" + "\n"
				+ "B) Carbon Dioxide \n" + "\n" + "C) Nitrous Oxide \n" + "\n" + "D) Sulfur Dioxide ");
		answerBank.put(4, "B");

		questionBank.put(5,
				"What is the most abundant renewable energy source on Earth? Please enter a letter.\n"
						+ "A) Wind Energy\n" + "\n" + "B) Hydropower\n" + "\n" + "C) Solar Energy\n" + "\n"
						+ "D) Geothermal Energy");
		answerBank.put(5, "C");

		questionBank.put(6,
				"Which of the following is NOT a renewable energy source? Please enter a letter.\n"
						+ "A) Wind Power\n"
						+ "\n" + "B) Natural Gas\n" + "\n" + "C) Hydroelectric Power\n" + "\n"
						+ "D) Geothermal Energy");
		answerBank.put(6, "B");

		questionBank.put(7,
				"What percentage of the world's electricity is currently generated by fossil fuels? PLease enter a letter.\n"
						+ "A) 20%\n" + "\n" + "B) 40%\n" + "\n" + "C) 60%\n" + "\n" + "D) 80%" + "\n");
		answerBank.put(7, "C");

		questionBank.put(8, "Which country generates the most electricity from wind energy? Please enter a letter.\n"
				+ "A) China\n" + "\n" + "B) Germany\n" + "'n" + "C) USA\n" + "\n" + "D) India");
		answerBank.put(8, "A");

		questionBank.put(9, "Which gas is the largest contributor to global warming? Please enter a letter.\n"
				+ "A) Oxygen\n" + "\n" + "B) Carbon Dioxide\n" + "\n" + "C) Nitrogen\n" + "\n" + "D) Methane");
		answerBank.put(9, "B");

		questionBank.put(10,
				"What is the main cause of ocean acidification? Please enter a letter.\n" + "A) Oil Spills\n" + "\n"
						+ "B) Plastic Pollution\n" + "\n" + "C) Increased CO₂ in the Atmosphere\n" + "\n"
						+ "D) Overfishing");
		answerBank.put(10, "C");

		questionBank.put(11,
				"Which sector is responsible for the most greenhouse gas emissions? Please enter a letter.\n"
						+ "A) Transportation\n" + "\n" + "B) Agriculture\n" + "\n" + "C) Industry\n" + "\n"
						+ "D) Energy Production");
		answerBank.put(11, "D");

		questionBank.put(12, "Which material takes the longest to decompose? Please enter a letter.\n"
				+ "A) Paper\n"
				+ "\n" + "B) Glass\n" + "\n" + "C) Plastic\n" + "\n" + "D) Aluminum");
		answerBank.put(12, "C");

		questionBank.put(13, "How many plastic bottles are thrown away every minute worldwide? Please enter a letter.\n"
				+ "A) 10,000\n" + "\n" + "B) 50,000\n" + "\n" + "C) 1 Million\n" + "\n" + "D) 5 Million");
		answerBank.put(13, "C");

		questionBank.put(14,
				"Which of the following is an example of 'reducing' waste? Please enter a letter.\n"
						+ "A) Buying a reusable water bottle instead of plastic ones\n" + "\n"
						+ "B) Throwing away old clothes\n" + "\n" + "C) Using more single-use plastics\n" + "\n"
						+ "D) Burning waste to generate heat");
		answerBank.put(14, "A");

		questionBank.put(15,
				"Which animal is considered a key indicator of climate change in the Arctic? Please enter a letter.\n"
						+ "A) Penguin\n" + "\n" + "B) Polar Bear\n" + "\n" + "C) Arctic Fox\n" + "\n"
						+ "D) Snow Leopard");
		answerBank.put(15, "B");

		questionBank.put(16,
				"Deforestation mainly occurs to make space for what? Please enter a letter.\n"
						+ "A) Renewable Energy Projects\n" + "\n" + "B) Urban Expansion\n"
						+ "\nC) Agriculture & Livestock Farming\n" + "\n" + "D) Tourism");
		answerBank.put(16, "C");

		questionBank.put(17,
				"Which of the following ecosystems stores the most carbon dioxide? Please enter a letter.\n"
						+ "A) Coral Reefs\n" + "\n" + "B) Deserts\n" + "\n" + "C) Tropical Rainforests\n" + "\n"
						+ "D) Grasslands");
		answerBank.put(17, "C");

		questionBank.put(18,
				"What is the biggest cause of biodiversity loss worldwide? Please enter a letter.\n"
						+ "A) Global Warming\n" + "\n" + "B) Habitat Destruction\n" + "\n" + "C) Overfishing\n" + "\n"
						+ "D) Pollution");
		answerBank.put(18, "B");

		questionBank.put(19, "Which of these countries has the highest renewable energy usage?\n"
				+ "A) USA \n" + "\n"
				+ "B) Germany \n" 
				+ "\n" + "C) Brazil \n" 
				+ "\n" + "D) China");
		answerBank.put(19, "C");
	}

	/**
	 * Method to generate a bank of ethical questions, to be called when a player
	 * wants to update to the highest development level.
	 */
	private void loadEthicsQuestions() {
		ethicsQuestionBank.put(1,
				"Is it ever justifiable to destroy a small forest if it provides economic growth to a struggling region? Please enter a letter.\n"
						+ "A) Yes, people’s economic needs should come first\n"
						+ "B) Only if efforts are made to replant trees\n"
						+ "C) Only if it's approved by local environmental scientists\n"
						+ "D) No, forests should never be destroyed");

		ethicsAnswerBank.put(1, "D");

		ethicsQuestionBank.put(2,
				"Who should bear the most responsibility for climate change? Please enter a letter.\n"
						+ "A) Individuals through daily habits\n" + "B) Large corporations and industrial producers\n"
						+ "C) Governments who regulate policies\n" + "D) All of the above equally");

		ethicsAnswerBank.put(2, "D");

		ethicsQuestionBank.put(3,
				"Is it ethical to mine rare earth minerals for clean energy tech if it harms local communities? Please enter a letter.\n"
						+ "A) Yes, because the end result helps the planet\n" + "B) No, the harm outweighs the good\n"
						+ "C) Only if those communities are compensated and consulted\n"
						+ "D) It depends on the global demand for clean energy");

		ethicsAnswerBank.put(3, "C");

		ethicsQuestionBank.put(4,
				"Should future generations have the same rights to natural resources as we do? Please enter a letter.\n"
						+ "A) No, they will innovate their own solutions\n" + "B) Yes, they deserve a healthy planet\n"
						+ "C) Only if resources are abundant\n" + "D) Not our responsibility");

		ethicsAnswerBank.put(4, "B");

		ethicsQuestionBank.put(5,
				"Is eating meat an ethical issue in the fight against climate change? Please enter a letter.\n"
						+ "A) No, personal diet is a private choice\n"
						+ "B) Yes, animal agriculture is a top emissions source\n"
						+ "C) Only if done in unsustainable ways\n"
						+ "D) Depends on culture and access to alternatives");

		ethicsAnswerBank.put(5, "B");

		ethicsQuestionBank.put(6,
				"Should developing countries be held to the same environmental standards as developed ones? Please enter a letter.\n"
						+ "A) No, it’s unfair\n" + "B) Yes, climate change affects us all\n"
						+ "C) Only with financial support from richer nations\n"
						+ "D) Only for industries that export goods");

		ethicsAnswerBank.put(6, "C");

		ethicsQuestionBank.put(7,
				"Would you support banning fast fashion to reduce environmental waste? Please enter a letter.\n"
						+ "A) No, it provides jobs\n" + "B) Yes, it’s extremely wasteful\n"
						+ "C) Only if sustainable options are affordable\n" + "D) No, people should be free to choose");

		ethicsAnswerBank.put(7, "C");

		ethicsQuestionBank.put(8,
				"If a country suffers severe drought, who should get priority access to water? Please enter a letter.\n"
						+ "A) Farmers\n" + "B) Households\n" + "C) Hospitals\n"
						+ "D) A balanced distribution based on need");

		ethicsAnswerBank.put(8, "D");

		ethicsQuestionBank.put(9,
				"Would you support strict laws to limit travel (e.g., flights) to reduce emissions? Please enter a letter.\n"
						+ "A) No, freedom of movement is a right\n"
						+ "B) Yes, drastic times call for drastic measures\n"
						+ "C) Only if clean transport is accessible\n" + "D) Only for non-essential travel");

		ethicsAnswerBank.put(9, "C");

		ethicsQuestionBank.put(10,
				"Should companies be legally required to publish their carbon footprint? Please enter a letter.\n"
						+ "A) No, that’s proprietary info\n" + "B) Yes, transparency leads to accountability\n"
						+ "C) Only if they’re government-funded\n" + "D) Only if consumers demand it");

		ethicsAnswerBank.put(10, "B");

	}

	public boolean askQuestion() {
		Random rand = new Random();

		List<Integer> questionIds = new ArrayList<>(questionBank.keySet());

		int questionNumber = rand.nextInt(questionIds.size());
		int questionId = questionIds.get(questionNumber);

		String question = questionBank.get(questionId);
		String correctAnswer = answerBank.get(questionId);

		if (question == null || correctAnswer == null) {
			System.err.println(" Error: Missing question or answer for ID " + questionId);
			return false;
		}

		System.out.println(question);
		System.out.print("Your answer:");
		System.out.print(" > ");
		
		String playerAnswer = scanner.nextLine().trim().toUpperCase();

		if (playerAnswer.equals(correctAnswer)) {
			System.out.println("Correct! Well Done " + CORRECT_MARK);
			return true;
		} else {
			System.out.println("Sorry, your answer was incorrect " + INCORRECT_MARK);
			return false;
		}
	}

	public boolean askEthicsQuestion() {
		Random randEthics = new Random();

		List<Integer> ethicsQuestionIds = new ArrayList<Integer>();

		int ethicsQuestionNumber = randEthics.nextInt(ethicsQuestionIds.size());
		int ethicsQuestionId = ethicsQuestionIds.get(ethicsQuestionNumber);

		String ethicsQuestion = ethicsQuestionBank.get(ethicsQuestionId);
		String correctEthicsAnswer = ethicsAnswerBank.get(ethicsQuestionId);

		if (ethicsQuestion == null || correctEthicsAnswer == null) {
			System.err.println(" Error: Missing question or answer for ID " + ethicsQuestionId);
			return false;
		}
		System.out.println(ethicsQuestion);
		System.out.print("Your answer:");
		System.out.print(" > ");
		
		String playerAnswer = scanner.nextLine().trim().toUpperCase();

		if (playerAnswer.equals(correctEthicsAnswer)) {
			System.out.println("Correct! Well Done " + CORRECT_MARK);
			return true;
		} else {
			System.out.println("Sorry, your answer was incorrect " + INCORRECT_MARK);
			return false;
		}
	}
}
